apiVersion: v1
kind: Service
metadata:
  name: mydep-service
spec:
  type: NodePort
  ports:
  - port: 8080         #service port
    targetPort: 8080   #Pod Port
    nodePort: 30088  #Node Port from the range - 30000-32767

  selector:
    app: my-dep
